Allow `pragma(mangle,...)` on an aggregate
dlang/dlang.org pull request #2875
Opened 2020-11-10 02:49 UTC by thewilsonator

see https://github.com/dlang/dmd/pull/11835

2020-12-14 10:02 UTC, WalterBright commented on spec/pragma.dd
> +        is treated as being a template with the signature and arguments of the TemplateInstance.
224-225 make no sense to me.

2020-12-14 10:02 UTC, WalterBright commented on spec/pragma.dd
> +    pragma(mangle, C.stringof, C)
I don't see how the third argument changes anything?

2021-03-24 23:52 UTC, Geod24 commented on spec/pragma.dd
> +>>>>>>> Allow `pragma(mangle,...)` on an aggregate
?

2021-03-25 00:25 UTC, thewilsonator commented on spec/pragma.dd
> +>>>>>>> Allow `pragma(mangle,...)` on an aggregate
accidentally committed half a merge conflict marker. fixed.

2021-05-21 07:35 UTC, mdparker requested changes

2021-05-21 07:35 UTC, mdparker commented on spec/pragma.dd
> +        For aggregates there may one or two $(ASSIGNEXPRESSION)s, one of which must evaluate at compile time to a string literal,
"literal, " -> "literal and"

2021-05-21 07:35 UTC, mdparker commented on spec/pragma.dd
> +        one which must evaluate to a symbol. If that symbol is a TemplateInstance the aggregate is treated as being a template
"TemplateInstance" should be italicized, and needs a comma.

2021-05-21 07:35 UTC, mdparker commented on spec/pragma.dd
> +        with the signature and arguments of the TemplateInstance. If no string is supplied the identifier of the symbol is used
"TemplateInstance" should be italicized.

2021-05-21 07:35 UTC, mdparker commented on spec/pragma.dd
> +        with the signature and arguments of the TemplateInstance. If no string is supplied the identifier of the symbol is used
"If no string is supplied the identifier of the symbol is used" -> "The identifier of the symbol is used when no string is supplied."

2021-05-21 07:35 UTC, mdparker commented on spec/pragma.dd
> +        one which must evaluate to a symbol. If that symbol is a TemplateInstance the aggregate is treated as being a template
"treated as being a" -> "treated as a"

2021-05-21 07:35 UTC, mdparker commented on spec/pragma.dd
> +        with the signature and arguments of the TemplateInstance. If no string is supplied the identifier of the symbol is used
"with the" -> "that has the"

2021-05-21 07:35 UTC, mdparker commented on spec/pragma.dd
> +        in its place. Both arguments may be used used when an aggregate has name that is a D keyword.
"an aggregate has name that is" -> "an aggregate's name is"

2021-07-05 12:22 UTC, RazvanN7 commented
@thewilsonator please apply the feedback.

2022-03-03 14:52 UTC, RazvanN7 approved these changes

2022-03-03 14:52 UTC, merged