fix Issue 3345: Static and nonstatic methods with the same name shoul…
dlang/dlang.org pull request #3080
Opened 2021-07-30 23:27 UTC by WalterBright

…d be allowed

This is how it was always designed, but never spec'ed.

2021-08-01 10:42 UTC, RazvanN7 requested changes

2021-08-01 10:42 UTC, RazvanN7 commented on spec/function.dd
> +        $(RATIONALE  This so a static member function that doesn't need
```suggestion
        $(RATIONALE  A static member function that doesn't need
```

2021-08-01 10:42 UTC, RazvanN7 commented on spec/function.dd
> +        function. The struct class
```suggestion
        function. The struct, class
```

2021-08-01 18:01 UTC, WalterBright commented
@RazvanN7 done

2021-08-02 08:04 UTC, RazvanN7 approved these changes

2021-08-02 08:04 UTC, merged