Update arrays.dd
dlang/dlang.org pull request #3095
Opened 2021-09-04 18:40 UTC by MrcSnm

Mention new expression for initializing dynamic array length

2021-09-06 18:44 UTC, dukc requested changes
I think this one better befits the "Array Initialization" section rather than the "Array properties" section.

2021-09-06 19:18 UTC, MrcSnm commented
> I think this one better befits the "Array Initialization" section rather than the "Array properties" section.

That section is actually `Setting Dynamic Array Length`. I didn't made into Array Initialization section because I saw it was only mentioning initializing it with data, and not its size.

2021-09-06 20:51 UTC, maxhaton commented
```
Searching for trailing whitespace
./spec/arrays.dd:782:        
./spec/arrays.dd:784:        
./spec/arrays.dd:789:        
./spec/arrays.dd:796:
```

Whitespace checker says jump, we have to say "how high?".

2021-09-06 21:09 UTC, MrcSnm commented
Did my best to edit it correctly, but idk how it really should be. Writing Ddoc is too strange for me yet

2021-09-06 21:30 UTC, maxhaton commented on spec/arrays.dd
> +
```suggestion

```
Little bit of trailing whitespace here

2021-09-07 11:11 UTC, dukc approved these changes

2021-09-07 13:29 UTC, maxhaton approved these changes

2021-09-07 13:29 UTC, merged