spec/lex.dd: Remove HexString from grammar
dlang/dlang.org pull request #3244
Opened 2022-03-06 21:20 UTC by ibuclaw

Hex strings have been obsolete since 2.086.

2022-03-06 21:45 UTC, maxhaton approved these changes
LGTM, haven't checked if the final website is sound yet

2022-03-07 11:12 UTC, ntrel requested changes
I suggest at least adding a link in the `\x` [string escape docs](https://github.com/dlang/dlang.org/blob/1d178c651e7f3a26ab61469ac99e69a1970aacb3/spec/lex.dd#L573):
```
See also: $(REF hexString, std,conv) 
```

2022-03-07 11:24 UTC, ntrel commented
> I suggest at least adding a link in the `\x` [string escape docs](https://github.com/dlang/dlang.org/blob/1d178c651e7f3a26ab61469ac99e69a1970aacb3/spec/lex.dd#L573):
> 
> ```
> See also: $(REF hexString, std,conv) 
> ```

Actually I can do it in another pull, I'm working on the escape sequence docs now anyway ;-)

2022-03-07 11:39 UTC, ntrel commented
Now done in #3245.

2022-03-07 20:22 UTC, merged