Fix Issue 23194 - Add ucora to list of companies using D
dlang/dlang.org pull request #3326
Opened 2022-06-23 02:40 UTC by maxhaton

2022-06-23 08:23 UTC, dkorpel requested changes

2022-06-23 08:23 UTC, dkorpel commented on orgs-using-d.dd
> +    $(DORG ucora, www.ucora.com, ucora.svg,
The link doesn't work, probably needs https://

2022-06-23 08:23 UTC, dkorpel commented on orgs-using-d.dd
> +        $(FA_QUOTE
The quote doesn't show up on the website

2022-06-23 08:23 UTC, dkorpel commented on orgs-using-d.dd
> +    )
There's no `$(LINK_ROW)`

2022-06-23 08:24 UTC, dkorpel commented
@mdparker I think it's up to you to approve the addition of this company.

2022-06-23 10:25 UTC, mdparker commented
@dkorpel Once the Ddoc stuff is good to go, please do give it the greenlight.

2022-06-23 13:42 UTC, maxhaton commented on orgs-using-d.dd
> +    )
They don't have much to link to

2022-06-25 16:08 UTC, BCPaulPaul commented
If it helps:

"Ucora Corporation"
"GamePlanPro(tm)"
"GamePlanPro™ is a mobile workflow platform for businesses of all sizes and types. 

Ucora is changing the way the world works."

The server platform is written entirely in D. 

https://www.ucora.com/solutions/software/
https://www.ucora.com/clients

Thank you

2022-06-25 16:23 UTC, maxhaton commented
Awesome

On Sat, 25 Jun 2022, 17:08 BCPaulPaul, ***@***.***> wrote:

> If it helps:
>
> "Ucora Corporation"
> "GamePlanPro(tm)"
> "GamePlanPro™ is a mobile workflow platform for businesses of all sizes
> and types.
>
> Ucora is changing the way the world works."
>
> The server platform is written entirely in D.
>
> https://www.ucora.com/solutions/software/
> https://www.ucora.com/clients
>
> Thank you
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dlang/dlang.org/pull/3326#issuecomment-1166317023>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABLI75BI5FLRBJ2XDJUS6STVQ4VJJANCNFSM5ZSVGUHQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-28 10:11 UTC, dkorpel commented
Ping @maxhaton

2022-07-29 08:15 UTC, RazvanN7 commented
@maxhaton any updates on this?

2022-08-10 09:43 UTC, RazvanN7 commented
@maxhaton can you take this to the finish line?

2022-08-10 14:58 UTC, maxhaton commented
```
make -fposix.mak html
.generated/stable_dmd-2.088.0/dmd2/linux/bin64/rdmd --compiler=.generated/stable_dmd-2.088.0/dmd2/linux/bin64/dmd -conf=.generated/stable_dmd-2.088.0/dmd2/linux/bin64/dmd.conf tools/ddoc_xml_extractor.d -i .generated/dblog_latest.xml -o .generated/dblog_latest.ddoc
No GC was initialized, please recheck the name of the selected GC ('conservative').
```
can't build the website anymore

2022-09-05 07:35 UTC, dkorpel commented
Superseded by https://github.com/dlang/dlang.org/pull/3402

2022-09-05 07:35 UTC, closed without merging