Fix download links
dlang/dlang.org pull request #3344
Opened 2022-07-19 12:35 UTC by ryuukk

2022-07-19 12:36 UTC, thewilsonator approved these changes

2022-07-19 13:05 UTC, merged

2022-07-19 15:13 UTC, ibuclaw requested changes

2022-07-19 15:13 UTC, ibuclaw commented on download.dd
> +    B_SUFFIX=beta.0
Aren't these numbers wrong? At the very least try a partial revert of the merge_stable commit rather than make it up.

2022-07-21 15:20 UTC, jmh530 commented
This only addresses the beta release.

2022-07-21 23:14 UTC, ibuclaw commented on download.dd
> +    B_SUFFIX=beta.0
🏥🎂👶