Clarify requirements for struct copy constructors
dlang/dlang.org pull request #3427
Opened 2022-10-02 21:12 UTC by pbackus

This change replaces informal language with official terms, adds cross-references, and documents a previously-undocumented requirement.

Fixes Issue 23382 - Non-template requirement for copy constructors is undocumented

2022-10-05 09:25 UTC, ntrel requested changes

2022-10-10 18:05 UTC, pbackus commented
CI failure is CircleCI failing to download `install.sh` due to an expired SSL certificate.

2022-10-12 20:44 UTC, ntrel approved these changes

2022-10-17 09:46 UTC, dkorpel approved these changes

2022-10-27 18:41 UTC, pbackus commented
Rebased to pick up #3434 via #3436.

2022-10-27 18:54 UTC, merged