Fixed issue  6583 - cast() operation not fully specified
dlang/dlang.org pull request #3502
Opened 2023-01-28 18:21 UTC by Robert21721

Added some information and examples about pointers and the casting process
 https://issues.dlang.org/show_bug.cgi?id=6583

2023-01-28 18:40 UTC, SixthDot requested changes

2023-01-28 18:40 UTC, SixthDot commented on spec/expression.dd
> +            // p = {97, 98, 99, 100, 101}
use square brackets please, so that this looks like a D array literal

2023-01-28 18:40 UTC, SixthDot commented on spec/expression.dd
> +            char* c = cast(char*) p;     // c = {97, 0, 0, 0, 98, 0, 0, 0, 99 ...}
same

2023-01-28 19:44 UTC, SixthDot commented
you need to reword the first commit message from "fixed ...." to "fix ...." so that the bot get triggered.

2023-01-28 20:14 UTC, SixthDot approved these changes
sorry for the last suggestion, that has not worked, the PR looks formally OK to me however.

2023-01-30 09:53 UTC, RazvanN7 commented
@Robert21721 changing the title of the PR is not going to trigger the bot. You need to add a commit (a.k.a git commit -m "Fix Issue 6583 - ...").

2023-01-30 10:11 UTC, RazvanN7 requested changes
This does not fully address the issue at hand. The following need to be treated for this PR to be accepted:

- casting a pointer type to a basic type
- casting a signed to an unsigned and vice-versa


As suggested in the issue, maybe these could be treated in related to what C does.

2023-01-30 10:11 UTC, RazvanN7 commented on spec/expression.dd
> +    )
I think this paragraph is a bit redundant. You don't need to explain every line of code, the example is fairly self explanatory.

2023-01-30 10:11 UTC, RazvanN7 commented on spec/expression.dd
> +    )
The above paragraph should simply state: "The following code results in undefined behavior due to accessing memory outside of the bounds of variable `c`".

2023-01-30 10:11 UTC, RazvanN7 commented on spec/expression.dd
> +    $(P The same thing can be done using a dynamically allocated array.)
The wording is not suitable for technical prose. Avoid using expressions such as "the same thing".

In this case you could word it as: "The same outcome can be obtained by using a dynamically allocated array".

However, the example does not present a case of undefined behavior. No out of bounds access is performed, therefore this example is not "the same" as the previous one.

2023-01-30 14:55 UTC, RazvanN7 commented on spec/expression.dd
> +    $(P Cast between different types of data will not be performed automatically.
This is too vague. One might get the impression that an `uint` must be cast to a `long`, which is not the case. This needs to be explained thoroughly. You can state that where [implicit conversions](https://dlang.org/spec/type.html#implicit-conversions) cannot be applied, casts may be used to force the type system to accept the reinterpretation. The int/byte example below is not necessary as it is thoroughly treated in the above link.

Then  you just need to explain the different types of casts that exist.

2023-01-30 15:04 UTC, RazvanN7 commented on spec/expression.dd
> +    $(P In this case, the sign will be extended.)
Please add a generalizing statement. I.E: "when casting an integral type from a narrower type to a wider type ... bla bla ... sign extension ... bla bla ".

Do not add meaningless paragraphs like this one.

2023-01-30 15:08 UTC, RazvanN7 commented on spec/expression.dd
> +        does not provide control over the obtained result.
Shouldn't this paragraph be merged with the "Pointers" section?

2023-01-30 15:09 UTC, RazvanN7 commented on spec/expression.dd
> +    )
Please be concise. You are talking about casting a pointer type to another pointer type. From your wording that is not obvious, sincer you can cast a pointer to another pointer or to a basic type, or to a class/struct (and the other way around).

2023-01-30 15:09 UTC, RazvanN7 commented on spec/expression.dd
> +    $(P The same outcome can be obtained by using a dynamically allocated array.)
This is too vague. What outcome are you referring to?

2023-01-30 15:12 UTC, RazvanN7 commented on spec/expression.dd
> +        outside of the bounds of variable c.
This should be a more general statement. For example: "When casting a pointer of type A to a pointer of type B and type B is wider than type A, if the portion of memory that exceeds the size of A is accessed, then that will result in undefined behavior.". This last sentence can still be improved, I meant it just as an example.

2023-01-31 10:33 UTC, RazvanN7 requested changes
Almost there.

2023-01-31 10:33 UTC, RazvanN7 commented on spec/expression.dd
> +        cannot be applied, so cast may be used to force the type system to accept the reinterpretation.
Rephrase to: "For situations where $(DDSUBLINK spec/type, implicit-conversions, implicit conversions)" on basic types cannot be performed, the type system may be forced to accept the reinterpretation of a memory region by using a cast.

2023-01-31 10:33 UTC, RazvanN7 commented on spec/expression.dd
> +        "cannot implicitly convert expression a of type int to byte".
Rephrase to: "An example of such a scenario is represented by trying to store a wider type into a narrower one:"

2023-01-31 10:33 UTC, RazvanN7 commented on spec/expression.dd
> +    byte b = a; // error
```suggestion
    byte b = a; // cannot implicitly convert expression a of type int to byte
```

2023-01-31 10:33 UTC, RazvanN7 commented on spec/expression.dd
> +    $(P When the destination type is smaller than the source type,
"When casting a source type that is wider than the destination type"

2023-01-31 10:33 UTC, RazvanN7 commented on spec/expression.dd
> +    $(P Casting from a narrower type to a wider type could be done automatically,
What does "could be done automatically mean" ? Is it done or is it not done?

I assume you want to say: "For integral types casting from a narrower type to a wider type is done by performing sign extension."

2023-01-31 11:18 UTC, RazvanN7 approved these changes
Squash the commits and we are ready to go.

2023-01-31 12:03 UTC, merged